global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - 'prometheus:9090' # prometheus on http://localhost:9090/metrics
  - job_name: node-exporter
    static_configs:
      - targets:
        - 'node-exporter:9100' # node-exporter on http://localhost:9100/metrics
  - job_name: postgres-exporter
    static_configs:
      - targets:
        - 'postgres-exporter:9187' # node-exporter on http://localhost:9187/metrics